name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Update version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          npm version $VERSION --no-git-tag-version

      - name: Build
        run: |
          VERSION=$(node -p "require('./package.json').version")
          DATE=$(date +%Y-%m-%d)
          # Build JS with copyright
          esbuild src/simple-select.js --bundle --minify --outfile=dist/simple-select.min.js --banner:js="/*!\n * Simple Select v${VERSION}\n * https://github.com/w-kuipers/simple-select\n * Copyright (c) 2024 Simple Select\n * Released under the MIT License\n * Date: ${DATE}\n */"
          # Build CSS with copyright
          echo "/*!\n * Simple Select v${VERSION}\n * https://github.com/w-kuipers/simple-select\n * Copyright (c) 2024 Simple Select\n * Released under the MIT License\n * Date: ${DATE}\n */" > dist/simple-select.min.css
          sass src/simple-select.scss --style compressed --no-source-map >> dist/simple-select.min.css

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload JS Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/simple-select.min.js
          asset_name: simple-select.min.js
          asset_content_type: application/javascript

      - name: Upload CSS Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/simple-select.min.css
          asset_name: simple-select.min.css
          asset_content_type: text/css
